openapi: 3.0.0

info:
  title: Test API 
  version: 0.1.0

paths:
  '/test/{test_id}':
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'schemas.yaml#/components/schemas/First'
        '400':
          content:
            application/json:
              schema:
                $ref: 'schemas.yaml#/components/schemas/First'

components:
  schemas:
    First:
      type: object 
      properties:
        foo:
          type: string

    Second:
      type: object
      properties:
        bar:
          type: string
